# Generated by Django 2.1 on 2018-08-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisesaying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.TextField(max_length=400),
        ),
    ]
